services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emc
      POSTGRES_PASSWORD: emc
      POSTGRES_DB: emtlab
    volumes:
      - pgdata_emtlab:/var/lib/postgresql/data
    ports:
      - "5434:5432"
volumes:
  pgdata_emtlab: